#!/system/bin/sh

PROP_NAME=$1
PROP_VALUE=$2

if [ "$PROP_NAME" == 'ro.kbc.propwritable' ]; then
    /system/bin/setprop persist.kbc.propwritable $PROP_VALUE
else
    PROP_WRITABLE=`getprop persist.kbc.propwritable`
    if [ "$PROP_WRITABLE" = '1' ]; then
        /sbin/setpropex $PROP_NAME $PROP_VALUE
    else
        /system/bin/setprop $PROP_NAME $PROP_VALUE
    fi
fi

